### ISSUE TITLE
How to pass custom fields in Preapproval request?

### ISSUE THREAD

**Issue by zohaibniaz** [angelleye/paypal-codeigniter#10]
I want to pass user_id in Preapproval request that can be used in ipn listener when buyer approve. 
How to do? @angelleye @decoxon

**Comment by angelleye** [comment]
The Preapproval API includes a CustomerID that PayPal labels as "your ID for the sender."  I believe this is what you're looking for, and if you provide that in the Preapproval request it would be included in the IPN associated with it.

Another option would be to add the user_id as a URL parameter on the IPNNotificationURL like this...

`'IPNNotificationURL' => 'http://sandbox.angelleye.com/paypal/ipn/ipn-listener.php?user_id=' . $user_id`

**Comment by zohaibniaz** [comment]
perfect......second option is working .....Thanks
