### ISSUE TITLE
Function Get_payment_options() returning error "Call to a member function getElementsByTagName() on string"

### ISSUE THREAD

**Issue by saikottakal** [angelleye/paypal-codeigniter#11]
Recently I got your package from GIT, and its working fine and thank you for your awesome work. When I tried to get the payment options using 'PayKey' am getting erro 'Call to a member function getElementsByTagName() on string' in Get_payment_options function. Can you please help me out to get rid of the same.

Thanks in Advance,
Sai

**Comment by angelleye** [comment]
Can you provide more details about that?  What file / line number is it referring to?

**Comment by saikottakal** [comment]
Thanks for your reply. I will send you a screenshot in a while.

**Comment by devchristina2** [comment]
Hi @saikottakal,

Thank you for reaching out and submitting an issue on our GitHub repository.

We wanted to inform you that we’ve temporarily paused active support for this repository and will close all open issues, including this one. If you require further assistance or have additional questions, please submit a support ticket through our [Help Center](https://angelleye.atlassian.net/servicedesk/customer/portals), where our support team will be happy to assist you.

We appreciate your understanding and apologize for any inconvenience. Thank you for being part of our community!

Thanks, Christina.
