### ISSUE TITLE
How to use PayPal Payouts?

### ISSUE THREAD

**Issue by zohaibniaz** [angelleye/paypal-codeigniter#12]
Can I use paypal payouts with this libraray??
if "yes" than how?

https://developer.paypal.com/docs/integration/direct/payouts/

@angelleye

**Comment by angelleye** [comment]
This library does not support REST.  However, we have been integrating all of the REST API calls into our [general PayPal PHP class library](https://github.com/angelleye/paypal-php-library).  We're about 80% done with that and will be releasing it soon.

It's the same library this CI specific library is based on, so it works exactly the same way, but you would need (or at least it would be recommended) to use Composer to load it up for use in CI.
