### ISSUE TITLE
Complex scenario for paypal

### ISSUE THREAD

**Issue by mzohaibniaz** [angelleye/paypal-codeigniter#13]
I am using paypal adaptive payments with Preapproval  request.
Buyer "A" buy 2 items from Seller '1' and  3 items from Seller '2'. Obviously, our app take commission from each seller. But this will be the preapproval request, buyer approve payments and after some days i.e. 20 we make an pay call and payments deducts.........

but the problem is, in this request there is two transactions 
1. Between app and seller 1
2. between app and seller 2

how to handle this in one transaction?

**Comment by devchristina2** [comment]
Hi @mzohaibniaz,

Thank you for reaching out and submitting an issue on our GitHub repository.

We wanted to inform you that we’ve temporarily paused active support for this repository and will close all open issues, including this one. If you require further assistance or have additional questions, please submit a support ticket through our [Help Center](https://angelleye.atlassian.net/servicedesk/customer/portals), where our support team will be happy to assist you.

We appreciate your understanding and apologize for any inconvenience. Thank you for being part of our community!

Thanks, Christina.
