### ISSUE TITLE
Message: Undefined index: surveyquestion - Paypal_pro.php

### ISSUE THREAD

**Issue by raknjak** [angelleye/paypal-codeigniter#14]
I just updated to version 3.0.0 of Paypal_pro but still get this message:

> A PHP Error was encountered
> Severity: Notice
> Message: Undefined index: surveyquestion
> Filename: paypal/Paypal_pro.php
> Line Number: 1385

I can fix this by doing this on line 1385:
`if(isset($SECFields['surveyquestion']) && $SECFields['surveyquestion'] != '')`

I did some Googling but could not find a previous report on this issue.
Thank you

**Comment by angelleye** [comment]
Thanks for letting us know.  We're really more focused on our [primary library](https://github.com/angelleye/paypal-php-library), and I believe we already fixed this there, but I'll double check.  That primary library could be used in CodeIgniter via Composer.

**Comment by raknjak** [comment]
thanks I'' just do that cheers
