### ISSUE TITLE
Undefined index: Ack

### ISSUE THREAD

**Issue by waqaszeeshanNetsol** [angelleye/paypal-codeigniter#15]
facing the following error, kindly help.

A PHP Error was encountered

Severity: Notice

Message: Undefined index: Ack

Filename: samples/Payments_pro.php

Line Number: 148

Backtrace:

File: /var/www/html/public/CodeIgniter/application/controllers/paypal/samples/Payments_pro.php
Line: 148
Function: _error_handler

File: /var/www/html/public/CodeIgniter/index.php
Line: 315
Function: require_once

**Comment by angelleye** [comment]
Can you verify what version of PHP and OpenSSL you are running on the server?

**Comment by waqaszeeshanNetsol** [comment]
php version 5.5.12.
right now i am running it on my localhost (wamp server)

**Comment by angelleye** [comment]
You need to get on 5.5.19 or higher.  Really at this point it's recommended to get on 7.0.  Also need to check the OpenSSL version.  

Based on the info you've provided it looks like your server is using the SSLv3 protocol instead of TLS 1.2, and PayPal only accepts traffic over TLS 1.2 now.

Updating to PHP 5.5.19+ and OpenSSL 1.0.1+ would resolve the issue.

**Comment by waqaszeeshanNetsol** [comment]
hi @angelleye 

my php version is: PHP Version 5.6.28

this is server infi:
Registered Stream Socket Transports	tcp, udp, unix, udg, ssl, sslv3, sslv2, tls, tlsv1.0, tlsv1.1, tlsv1.2

openssl
OpenSSL support 	enabled
OpenSSL Library Version 	OpenSSL 1.0.1e-fips 11 Feb 2013
OpenSSL Header Version 	OpenSSL 1.0.1e-fips 11 Feb 2013
Openssl default config 	/etc/pki/tls/openssl.cnf

**Comment by angelleye** [comment]
So you've got that and you're still getting an empty result?

**Comment by waqaszeeshanNetsol** [comment]
$PayPalResult array returning this :

Array
(
    [ERRORS] => Array
        (
        )

    [REQUESTDATA] => Array
        (
            [USER] => waqas_api1.netsol.com
            [PWD] => MW45NATV82A4Z36F
            [VERSION] => 123.0
            [BUTTONSOURCE] => AngellEYE_PHPClass
            [SIGNATURE] => AFcWxV21C7fd0V1KbZmUwLaxmUP502GLHSuXp
            [METHOD] => DoDirectPayment
            [PAYMENTACTION] => Sale
            [IPADDRESS] => 10.12.10.15
            [RETURNFMFDETAILS] => 1
            [CREDITCARDTYPE] => MasterCard
            [ACCT] => 5424180818927383
            [EXPDATE] => 102017
            [CVV2] => 123
            [EMAIL] => test@domain.com
            [BUSINESS] => Testers, LLC
            [SALUTATION] => Mr.
            [FIRSTNAME] => Tester
            [LASTNAME] => Testerson
            [STREET] => 123 Test Ave.
            [CITY] => Kansas City
            [STATE] => MO
            [COUNTRYCODE] => US
            [ZIP] => 64111
            [PHONENUM] => 555-555-5555
            [AMT] => 100.00
            [CURRENCYCODE] => USD
            [ITEMAMT] => 95.00
            [SHIPPINGAMT] => 5.00
            [DESC] => Web Order
            [L_NAME0] => Test Widget 123
            [L_DESC0] => The best test widget on the planet!
            [L_AMT0] => 95.00
            [L_NUMBER0] => 123
            [L_QTY0] => 1
            [SHIPTONAME] => Tester Testerson
            [SHIPTOSTREET] => 123 Test Ave.
            [SHIPTOCITY] => Kansas City
            [SHIPTOSTATE] => MO
            [SHIPTOZIP] => 64111
            [SHIPTOCOUNTRY] => US
            [SHIPTOPHONENUM] => 555-555-5555
        )

    [RAWREQUEST] => USER=waqasapi1.netsol.com&PWD=MW45NATV82A4Z36F&VERSION=123.0&BUTTONSOURCE=AngellEYE_PHPClass&SIGNATURE=AFcWxV21C7fd0UwLaxmUP502GLHSuXp&METHOD=DoDirectPayment&PAYMENTACTION=Sale&IPADDRESS=10.12.10.15&RETURNFMFDETAILS=1&CREDITCARDTYPE=MasterCard&ACCT=5424180818927383&EXPDATE=102017&CVV2=123&EMAIL=test%40domain.com&BUSINESS=Testers%2C+LLC&SALUTATION=Mr.&FIRSTNAME=Tester&LASTNAME=Testerson&STREET=123+Test+Ave.&CITY=Kansas+City&STATE=MO&COUNTRYCODE=US&ZIP=64111&PHONENUM=555-555-5555&AMT=100.00&CURRENCYCODE=USD&ITEMAMT=95.00&SHIPPINGAMT=5.00&DESC=Web+Order&L_NAME0=Test+Widget+123&L_DESC0=The+best+test+widget+on+the+planet%21&L_AMT0=95.00&L_NUMBER0=123&L_QTY0=1&SHIPTONAME=Tester+Testerson&SHIPTOSTREET=123+Test+Ave.&SHIPTOCITY=Kansas+City&SHIPTOSTATE=MO&SHIPTOZIP=64111&SHIPTOCOUNTRY=US&SHIPTOPHONENUM=555-555-5555
    [RAWRESPONSE] => 
)

**Comment by waqaszeeshanNetsol** [comment]
@angelleye 
$PayPalResult['Ack'] is not in the array so i am getting error

**Comment by angelleye** [comment]
Right, and that's becuase RAWRESPONSE is empty.  You'll need to look at curl_error to figure out why it's failing.  Are you familiar with that?

**Comment by waqaszeeshanNetsol** [comment]
no i am not familiar..!

**Comment by angelleye** [comment]
I can help you with that, but it's beyond the scope of what I can do for free support.  If you'd like me to figure out what's going on for you please [submit an order for general consulting](https://www.angelleye.com/product/paypal-help/).
