### ISSUE TITLE
How to verify user email exist or not on paypal?

### ISSUE THREAD

**Issue by zohaibniaz** [angelleye/paypal-codeigniter#16]
I want to verify that the receiver email exist or not on paypal.
how to do? @angelleye @decoxon

**Comment by nomi416** [comment]
You can use  function "GetVerifiedStatus" in adaptive payments library. It will return account status if its exists or error if it does not.

**Comment by zohaibniaz** [comment]
Thanks !! but this is checking with "NAME"; I want to check with email only

**Comment by zohaibniaz** [comment]
i there any method to get status with email only? @angelleye @decoxon @nomi416

**Comment by zohaibniaz** [comment]
thanks
