### ISSUE TITLE
Send payment to single receiver in Adaptive payment

### ISSUE THREAD

**Issue by nomi416** [angelleye/paypal-codeigniter#17]
Hi!
I am using Pay function to send payment to single receiver. I modified the function pay_chained in sample and set only one receiver but it throwing error. 
`'ErrorID' => string '520002'
'Message' => string 'Internal Error'`

Please help me solve this issue as i don't know whats wrong with it.

Thanks

**Comment by angelleye** [comment]
When you changed it to one receiver did you make sure to remove the primary flag?

**Comment by devchristina2** [comment]
Hi @nomi416,

Thank you for reaching out and submitting an issue on our GitHub repository.

We wanted to inform you that we’ve temporarily paused active support for this repository and will close all open issues, including this one. If you require further assistance or have additional questions, please submit a support ticket through our [Help Center](https://angelleye.atlassian.net/servicedesk/customer/portals), where our support team will be happy to assist you.

We appreciate your understanding and apologize for any inconvenience. Thank you for being part of our community!

Thanks, Christina.
