### ISSUE TITLE
Sample adaptive payments API call return error: 520002

### ISSUE THREAD

**Issue by ahkmunna** [angelleye/paypal-codeigniter#18]
I'm trying to install the adaptive payments in my application when i try the sample code it give error bellow: 
Array
(
    [0] => Array
        (
            [Receiver] => 
            [Category] => Application
            [Domain] => PLATFORM
            [ErrorID] => 520002
            [ExceptionID] => 
            [Message] => Internal Error
            [Parameter] => 
            [Severity] => Error
            [Subdomain] => Application
        )

)

**Comment by nomi416** [comment]
I am getting the same error. But in my case, sample code runs fine. But when i copy the same code inside my project, (after checking account status for user email and user's account status if verified). it throws that error.

**Comment by nomi416** [comment]
I was able to solve my problem. I was loading library in function. I moved it to constructor of controller and it started working.
