### ISSUE TITLE
Data validation warning(line 1, col 1,829): String "TRUE" is not valid boolean value

### ISSUE THREAD

**Issue by munemkhetran** [angelleye/paypal-codeigniter#20]
i have facing this issue @angelleye  @decoxon 
error:
Data validation warning(line 1, col 1,829): String "TRUE" is not valid boolean value

**Comment by angelleye** [comment]
I'm sorry for the delay responding.  Were you able to get passed this or are you still struggling with it?

**Comment by munemkhetran** [comment]
thanks for responding me
i solved my issue.
