### ISSUE TITLE
How to make chained payment ?

### ISSUE THREAD

**Issue by soravgarg123** [angelleye/paypal-codeigniter#22]
Hello,

I am using parallel payment using Paypal_adaptive.php library but parallel payment showing recievers info while checkout so  i want to hide receiver info while payment so paypal team has suggest me to use chained payment instead of parallel, so can you help me using this library or code how i can use chained payment ? please reply me as soon as.

Thanks

**Comment by angelleye** [comment]
For a regular chained payment you just need to make sure and set one of the receivers as primary in your request.  For example, if we setup $Receivers like this:

```
$Receivers = array();
$Receiver = array(
    'Amount' => '10.00', 											// Required.  Amount to be paid to the receiver.
    'Email' => 'sandbo_1204199080_biz@angelleye.com', 												// Receiver's email address. 127 char max.
    'AccountID' => '',                                          // Receiver's PayPal account ID.
    'InvoiceID' => '', 											// The invoice number for the payment.  127 char max.
    'PaymentType' => '', 										// Transaction type.  Values are:  GOODS, SERVICE, PERSONAL, CASHADVANCE, DIGITALGOODS
    'PaymentSubType' => '', 									// The transaction subtype for the payment.
    'Phone' => array('CountryCode' => '', 'PhoneNumber' => '', 'Extension' => ''), // Receiver's phone number.   Numbers only.
    **'Primary' => TRUE**												// Whether this receiver is the primary receiver.  Values are boolean:  TRUE, FALSE
);
array_push($Receivers,$Receiver);
$Receiver = array(
    'Amount' => '5.00', 											// Required.  Amount to be paid to the receiver.
    'Email' => 'usb_1329725429_biz@angelleye.com', 												// Receiver's email address. 127 char max.
    'AccountID' => '',                                          // Receiver's PayPal account ID.
    'InvoiceID' => '123-ABCDEF', 											// The invoice number for the payment.  127 char max.
    'PaymentType' => '', 										// Transaction type.  Values are:  GOODS, SERVICE, PERSONAL, CASHADVANCE, DIGITALGOODS
    'PaymentSubType' => '', 									// The transaction subtype for the payment.
    'Phone' => array('CountryCode' => '', 'PhoneNumber' => '', 'Extension' => ''), // Receiver's phone number.   Numbers only.
    'Primary' => ''												// Whether this receiver is the primary receiver.  Values are boolean:  TRUE, FALSE
);
array_push($Receivers,$Receiver);
```

This would result in a chained payment where the funds go through the primary receiver's account.

**Comment by soravgarg123** [comment]
Hello,

Thanks for reply.

So for chained paymen will need to change ActionType to PAY_PRIMARY right ?

and also will need to define primary reciever ?

and how we will secondary receiver would not be paid until you call ExecutePayment to release those funds ?

can you show me a example of whole code, to my issue, it would be very help full or i need to show my code and then you will modify my code ?

**Comment by angelleye** [comment]
A regular chained payment does not need PAY_PRIMARY.  It only needs a primary receiver set in the $Receivers array.

A delayed chained payment would require PAY_PRIMARY.

I could put together a demo with complete flow for you but I'd need you to [submit an order for consulting](https://www.angelleye.com/product/paypal-help/) to do that.  It sounds like you basically have it, though.  You just need to follow the info above.
