### ISSUE TITLE
I Want A Code For Parallel Payment

### ISSUE THREAD

**Issue by SanjuDev** [angelleye/paypal-codeigniter#23]
Hello,
I m trying to configure 'paypal adaptive payment gateway' with 'parallel payment' method, so anybody can help me for that.
I configured all the basic things.
there is no demo function available for parallel payment in this sample code, only available for 'chained payment'.
#,http://elh.khasrabrothers.in/paypal/samples/Adaptive_payments
It is working fine as demo But i want to pay payment to two person 25% for one and 75% for another person, that's why i thing so it is possible with parallel method.

**Comment by angelleye** [comment]
The Adaptive Payments platform is now fully deprecated and they are no longer issuing live App IDs for it.  You can do a Parallel Payment with Express Checkout, though, which provides a better checkout experience anyway.  That's what I would recommend.

If you check out demo kits you'll find this:  https://www.angelleye.com/product/codeigniter-paypal-integration-express-checkout-line-items-demo/

That will show you how Express Checkout works in general, and within that you'll see that it has a $Payments array.  In the demo it's only using a single payment, but all you have to do is add additional $Payment arrays to the $Payments array, and that would be a parallel payment at that point.
