### ISSUE TITLE
Payment Functioning

### ISSUE THREAD

**Issue by SanjuDev** [angelleye/paypal-codeigniter#24]
I m using sandbox account for adaptive payment (Parallel Payment) and I m using your SDK in CI. it is really nice but m unable to understand how payment functioning will work because when i m trying to login for payment it says 'unable to payment'.
can u please provide me some solution for this 
Link: http://elh.khasrabrothers.in/paypal/samples/adaptive_payments/pay_parallel
Please reply me as soon as possible

**Comment by angelleye** [comment]
Do you have a live App ID for Adaptive already?  They have officially closed that and are not providing live App IDs anymore, so unless you already have one you should use Express Checkout instead of Adaptive.

**Comment by devchristina2** [comment]
Hi @SanjuDev,

Thank you for reaching out and submitting an issue on our GitHub repository.

We wanted to inform you that we’ve temporarily paused active support for this repository and will close all open issues, including this one. If you require further assistance or have additional questions, please submit a support ticket through our [Help Center](https://angelleye.atlassian.net/servicedesk/customer/portals), where our support team will be happy to assist you.

We appreciate your understanding and apologize for any inconvenience. Thank you for being part of our community!

Thanks, Christina.
