### ISSUE TITLE
Save Data In DB

### ISSUE THREAD

**Issue by SanjuDev** [angelleye/paypal-codeigniter#25]
Hello Sir,
After successful of adaptive payment (parallel payment), how to save data in my DB?
please reply me as soon as possible.
thanks

**Comment by angelleye** [comment]
Do you have a live App ID for Adaptive already? They have officially closed that and are not providing live App IDs anymore, so unless you already have one you should use Express Checkout instead of Adaptive.

**Comment by angelleye-gitcommits** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done

<hr>

**This issue now has a bounty of $50.00 attached to it.**

- If you would like to work on this issue you can 'start work' [on the GitCommits Issue Details page](https://sandbox.app.gitcommits.com/issue/test-title).
- Questions? Checkout [GitCommits Help](https://sandbox.gitcommits.com/help)
- More funded Bounties are available on the [GitCommits Issue Explorer](https://sandbox.app.gitcommits.com/explorer)

**Comment by devchristina2** [comment]
Hi @SanjuDev,

Thank you for reaching out and submitting an issue on our GitHub repository.

We wanted to inform you that we’ve temporarily paused active support for this repository and will close all open issues, including this one. If you require further assistance or have additional questions, please submit a support ticket through our [Help Center](https://angelleye.atlassian.net/servicedesk/customer/portals), where our support team will be happy to assist you.

We appreciate your understanding and apologize for any inconvenience. Thank you for being part of our community!

Thanks, Christina.
