### ISSUE TITLE
Test issue in public repo

### ISSUE THREAD

**Issue by deepakmaurya** [angelleye/paypal-codeigniter#29]
This is a test, please ignore it.

**Comment by angelleye-gitcommits** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done

<hr>

**This issue now has a bounty of $10.00 attached to it.**

- If you would like to work on this issue you can 'start work' [on the GitCommits Issue Details page](https://sandbox.app.gitcommits.com/issue/fix-my-website-footer).
- Questions? Checkout [GitCommits Help](https://sandbox.app.gitcommits.com/help) or the [GitCommits Slack](https://sandbox.app.gitcommits.com/slack)
- More funded Bounties are available on the [GitCommits Issue Explorer](https://sandbox.app.gitcommits.com/explorer)

**Comment by angelleye-gitcommits** [comment]
Issue Status: 1. Open 2. **Started**  3. Submitted 4. Done

<hr>

**Work has been started.**

**<a href='https://sandbox.app.gitcommits.com/profile/deepakmaurya'>deepakmaurya</a> has been approved to start work.**

<hr />

**Message:** Sure start the work.


<a href='https://sandbox.app.gitcommits.com/issue/fix-my-website-footer'>Click Here to view more</a> on GitCommits Bounty detail page.

**Comment by angelleye-gitcommits** [comment]
**Work has been submitted by <a href='https://sandbox.app.gitcommits.com/profile/deepakmaurya'>deepakmaurya</a>.**
<hr />

**Message:** task is completed, please approve and pay. thanks


<a href='https://sandbox.app.gitcommits.com/issue/fix-my-website-footer'>Click Here to view more</a> on GitCommits Bounty detail page.

**Comment by angelleye-gitcommits** [comment]
**<a href='https://sandbox.app.gitcommits.com/profile/deepakmaurya'>deepakmaurya</a> Work has been approved by <a href='maurya'>https://sandbox.app.gitcommits.com/profile/maurya</a>.**
<hr />

**Message:** Thank you for great work. I just released the payment.


<a href='https://sandbox.app.gitcommits.com/issue/fix-my-website-footer'>Click Here to view more</a> on GitCommits Bounty detail page.

**Comment by angelleye-gitcommits** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done

<hr>

**This issue now has a bounty of $20.00 attached to it.**

- If you would like to work on this issue you can 'start work' [on the GitCommits Issue Details page](https://sandbox.app.gitcommits.com/issue/second-funded-issue).
- Questions? Checkout [GitCommits Help](https://sandbox.app.gitcommits.com/help) or the [GitCommits Slack](https://sandbox.app.gitcommits.com/slack)
- More funded Bounties are available on the [GitCommits Issue Explorer](https://sandbox.app.gitcommits.com/explorer)

**Comment by angelleye-gitcommits** [comment]
Issue Status: 1. Open 2. **Started**  3. Submitted 4. Done

<hr>

**Work has been started.**

**<a href='https://sandbox.app.gitcommits.com/profile/deepakmaurya'>deepakmaurya</a> has been approved to start work.**

<hr />

**Message:** sure, you are approved to work on this issue.


<a href='https://sandbox.app.gitcommits.com/issue/second-funded-issue'>Click Here to view more</a> on GitCommits Bounty detail page.

**Comment by angelleye-gitcommits** [comment]
**<a href='https://sandbox.app.gitcommits.com/profile/deepakmaurya'>deepakmaurya</a> Work has been approved by <a href='maurya'>https://sandbox.app.gitcommits.com/profile/maurya</a>.**
<hr />

**Message:** payment done


<a href='https://sandbox.app.gitcommits.com/issue/second-funded-issue'>Click Here to view more</a> on GitCommits Bounty detail page.
