### ISSUE TITLE
probably SSL caused issue

### ISSUE THREAD

**Issue by kelemenbalazs** [angelleye/paypal-codeigniter#6]
I am getting that issue same as mentioned in the link below, while im tryiong to create a chained payment for PAY_PRIMARY.

http://stackoverflow.com/questions/26789743/paypal-sandbox-api-status

 I am not sure, how to solve that problem, thats why i created this card.

I am using the adaptive payments for create chained payments, it was worked yesterday, but now i get empty response from the sandbox. 

Thanks forward: Balazs

**Comment by angelleye** [comment]
Please review this post:  https://www.angelleye.com/paypal-ssl-error-poodle-vulnerability/

Then let me know if you have any specific questions after that.

**Comment by devchristina2** [comment]
Hi @kelemenbalazs,

Thank you for reaching out and submitting an issue on our GitHub repository.

We wanted to inform you that we’ve temporarily paused active support for this repository and will close all open issues, including this one. If you require further assistance or have additional questions, please submit a support ticket through our [Help Center](https://angelleye.atlassian.net/servicedesk/customer/portals), where our support team will be happy to assist you.

We appreciate your understanding and apologize for any inconvenience. Thank you for being part of our community!

Thanks, Christina.
