### ISSUE TITLE
How to set shipping fee in paypal request 

### ISSUE THREAD

**Issue by mzohaibniaz** [angelleye/paypal-codeigniter#7]
i m using this library for paypal adaptive payments. I want to set shipping fee with api call. i see there is no option for shipping in samples. so plz guide

**Comment by angelleye** [comment]
Take a look at the PayWithOptions.php sample/template.

**Comment by angelleye** [comment]
Just remembered I don't have that included in the CodeIgniter library.  It's supported, I just don't have the sample.

Take a look at PayWithOptions from our general library:  https://github.com/angelleye/paypal-php-library/blob/dev/samples/PayWithOptions.php

It's the same library as this, but it's not specific to CodeIgniter.  You'll just need to build the same function into your controller the way the other calls are done.

**Comment by zohaibniaz** [comment]
its giving me error -- receiver fields must contain one receiver

**Comment by angelleye** [comment]
Well that's a pretty straight forward error.  You must be passing in a $Receivers array without any receivers setup in it..??

**Comment by devchristina2** [comment]
Hi @mzohaibniaz,

Thank you for reaching out and submitting an issue on our GitHub repository.

We wanted to inform you that we’ve temporarily paused active support for this repository and will close all open issues, including this one. If you require further assistance or have additional questions, please submit a support ticket through our [Help Center](https://angelleye.atlassian.net/servicedesk/customer/portals), where our support team will be happy to assist you.

We appreciate your understanding and apologize for any inconvenience. Thank you for being part of our community!

Thanks, Christina.
