### ISSUE TITLE
Invalid request parameter: institutionId with value <value>

### ISSUE THREAD

**Issue by zohaibniaz** [angelleye/paypal-codeigniter#8]
these are the required fields but it does not accept any value and giving me
Invalid request parameter: institutionId with value 786
how to fix? and what is institutionId ?

**Comment by angelleye** [comment]
That's only required if you include that particular set of parameters.  

You'll notice there's an $InstitutionCustomer array included and within that you'll find the InstitutionID along with other related parameters.  Just eliminate $InstitutionCustomer from the  $PayPalRequestData altogether and that will go away.  You can just comment it out of $PayPalRequestData.

I recommend starting with as few params as necessary.  Then slowly add things from there.
