### ISSUE TITLE
The URL /paypal/adaptive_payments/pay_cancel is malformed

### ISSUE THREAD

**Issue by mscarchilli** [angelleye/paypal-codeigniter#9]
I keep getting that the CancelURL is malformed. I have tried multiple URL's with no success. What could I be doing wrong here?

```
Array
(
    [0] => Array
        (
            [Receiver] => 
            [Category] => Application
            [Domain] => PLATFORM
            [ErrorID] => 580028
            [ExceptionID] => 
            [Message] => The URL /paypal/adaptive_payments/pay_cancel is malformed
            [Parameter] => /paypal/adaptive_payments/pay_cancel
            [Severity] => Error
            [Subdomain] => Application
        )

)
```

These do work from the demos.
- Payments Pro - GetBalance
- Adaptive Payments - ConvertCurrency

**Comment by angelleye** [comment]
Need to see the raw request log so we can see what value is getting included for the CancelURL.

**Comment by devchristina2** [comment]
Hi @mscarchilli,

Thank you for reaching out and submitting an issue on our GitHub repository.

We wanted to inform you that we’ve temporarily paused active support for this repository and will close all open issues, including this one. If you require further assistance or have additional questions, please submit a support ticket through our [Help Center](https://angelleye.atlassian.net/servicedesk/customer/portals), where our support team will be happy to assist you.

We appreciate your understanding and apologize for any inconvenience. Thank you for being part of our community!

Thanks, Christina.
